### ISSUE TITLE
fix(calculo): bug ao realizar novas operações

### ISSUE THREAD

**Issue by denilsonpy** [Ghabriel-elias/projeto-calculadora-js#1]
Após realizar a primeira operação e apagar o valor atual com o botão de delete ao realizar a nova operação o cálculo acaba ficando estranho:

1 - Realize a operação `8 × 9`:

![Captura de tela de 2022-10-16 22-47-20](https://user-images.githubusercontent.com/82189418/196072182-eceef3a3-3821-4879-8ffe-11588b784f07.png)

2 - Apague com o delete

3 - Realize a operação `8 × 9` novamente

![Captura de tela de 2022-10-16 22-47-33](https://user-images.githubusercontent.com/82189418/196072333-3704aaf7-8694-4214-9929-46e99f63ea04.png)

**Comment by Ghabriel-elias** [comment]
Valeu pelo feedback man, vou tentar corrigir esse bug, ja entendi como q
ele funciona :)

Em dom., 16 de out. de 2022 21:50, Denilson Martins <
***@***.***> escreveu:

**Comment by Ghabriel-elias** [comment]
Creio eu que o bug foi solucionado;)

Em dom., 16 de out. de 2022 22:01, Denilson Martins <
***@***.***> escreveu:

**Comment by denilsonpy** [comment]
Boaa, parabéns :D
